#!/bin/bash
PATH=/bin:/usr/bin


should_exclude() {
    echo $* | grep -qE 'make_wrapper'
}

echo "// Autogenerated at `date`"
echo "// DO NOT MANUALLY EDIT THIS FILE"
echo

for f in $*; do
    if should_exclude $f; then
        continue;
    fi;
	echo "#include \"$f\""
done
echo

echo "int main(int argc, char *argv[])"
echo -n "{"

for f in $*; do
    if should_exclude $f; then
        continue;
    fi;
	className=`basename $f .h`
	echo
	echo "    $className test_$className;"
	echo "    QTest::qExec(&test_$className, argc, argv);"
done

echo "}"
